### ISSUE TITLE
Jazz could not compile with elixir v1.5.1

### ISSUE THREAD

**Issue by zentechthaingo** [meh/jazz#16]
warning: the dependency :jazz requires Elixir "~> 1.0.0-rc1" but you are running on v1.5.1
`== Compilation error in file lib/jazz/encoder.ex ==
** (CompileError) lib/jazz/encoder.ex:55: inlined function indentation/1 undefined
    (stdlib) lists.erl:1338: :lists.foreach/2
    lib/jazz/encoder.ex:55: (file)`

could not compile dependency :jazz, "mix compile" failed. You can recompile this dependency with "mix deps.compile jazz", update it with "mix deps.update jazz" or clean it with "mix deps.clean jazz"

**Comment by LinuxSystemAdmin** [comment]
I am also having this issue at Ubuntu 16.04 

![screenshot from 2018-01-09 23-11-23](https://user-images.githubusercontent.com/32417351/34733412-73a5d194-f592-11e7-8963-06306bb348a4.png)

**Comment by lowks** [comment]
I am also having this issue on latest mac. `High Sierra 10.13.5`
Elixir version: `1.6.1`
Elixir installed using `asdf`

**Comment by auser** [comment]
ditto. :(

**Comment by meh** [comment]
Fixed.
